//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioMTPrep
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioMTPrep.IServicioMT")]
    public interface IServicioMT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMT/fnAutenticacion", ReplyAction="http://tempuri.org/IServicioMT/fnAutenticacionResponse")]
        System.Threading.Tasks.Task<string> fnAutenticacionAsync(string PI_DatosXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMT/fnEjecutaTransaccion", ReplyAction="http://tempuri.org/IServicioMT/fnEjecutaTransaccionResponse")]
        System.Threading.Tasks.Task<string> fnEjecutaTransaccionAsync(string PI_DatosXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMT/fnLoginAplicacion", ReplyAction="http://tempuri.org/IServicioMT/fnLoginAplicacionResponse")]
        System.Threading.Tasks.Task<string> fnLoginAplicacionAsync(string PI_DatosXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMT/fnCambioClave", ReplyAction="http://tempuri.org/IServicioMT/fnCambioClaveResponse")]
        System.Threading.Tasks.Task<string> fnCambioClaveAsync(string PI_DatosXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMT/fnRegistroPersona", ReplyAction="http://tempuri.org/IServicioMT/fnRegistroPersonaResponse")]
        System.Threading.Tasks.Task<string> fnRegistroPersonaAsync(string PI_DatosXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioMTChannel : servicioMTPrep.IServicioMT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioMTClient : System.ServiceModel.ClientBase<servicioMTPrep.IServicioMT>, servicioMTPrep.IServicioMT
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioMTClient() : 
                base(ServicioMTClient.GetDefaultBinding(), ServicioMTClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioMT.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMTClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioMTClient.GetBindingForEndpoint(endpointConfiguration), ServicioMTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioMTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioMTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> fnAutenticacionAsync(string PI_DatosXml)
        {
            return base.Channel.fnAutenticacionAsync(PI_DatosXml);
        }
        
        public System.Threading.Tasks.Task<string> fnEjecutaTransaccionAsync(string PI_DatosXml)
        {
            return base.Channel.fnEjecutaTransaccionAsync(PI_DatosXml);
        }
        
        public System.Threading.Tasks.Task<string> fnLoginAplicacionAsync(string PI_DatosXml)
        {
            return base.Channel.fnLoginAplicacionAsync(PI_DatosXml);
        }
        
        public System.Threading.Tasks.Task<string> fnCambioClaveAsync(string PI_DatosXml)
        {
            return base.Channel.fnCambioClaveAsync(PI_DatosXml);
        }
        
        public System.Threading.Tasks.Task<string> fnRegistroPersonaAsync(string PI_DatosXml)
        {
            return base.Channel.fnRegistroPersonaAsync(PI_DatosXml);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMT))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMT))
            {
                return new System.ServiceModel.EndpointAddress("http://200.24.198.70/WCFMT_PREP/ServicioMT.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioMTClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioMT);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioMTClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioMT);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioMT,
        }
    }
}
